#!/bin/bash
set -e

envsubst < /config/ssmtp.conf > /etc/ssmtp/ssmtp.conf

if [ ! -z $PHP_FPM_GID ]; then
    groupmod -g $PHP_FPM_GID -o www-data
fi

if [ ! -z $PHP_FPM_UID ]; then
    usermod -u $PHP_FPM_UID -o www-data
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi
exec "$@"
